version: '3'
services:
  web:
    image: myregistry.azurecr.io/my-project-repo:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TEST_TEST=testtesttest
      - PG_USER=value_of_server_admin_login # optional if you don't want to test postgres connection
      - PG_PASS=xxxxxxxxxxxxxxx             # optional if you don't want to test postgres connection
      - PG_HOST=value_of_server_name        # optional if you don't want to test postgres connection
    ports:
      - "2222:2222"
      - "80:80"    # or this can be "3000:80" if your localhost machin blocks port 80
